database init
Mazart23/pet_book pull request #2
Opened 2024-10-28 21:29 UTC by julkry

Changes:
- __init__.py for database
- simple query in queries.py
- /user endpoint for testing database connection
- pymongo in requirements.txt

2024-10-29 10:09 UTC, Mazart23 requested changes
Generalnie git, spoko wszystko zrobione ale parę rzeczy do zweryfikowania

2024-10-29 10:36 UTC, julkry commented on controller/requirements.txt
> +pymongo==4.4.0
mi wszystko normalnie poszlo i swagger działał

2024-10-29 10:42 UTC, julkry commented on controller/src/database/queries.py
> +            query = {'_id': ObjectId(id)}
automatycznie dodawane id w mongodb sa typu ObjectId - bez tego nie znajdzie elementu, a przynajmniej ja nie znalazlam takiego sposobu

2024-10-29 10:48 UTC, julkry commented on controller/src/database/__init__.py
> +    def fetch_all(self, cursor):
to jest to co zwraca find(), zeby wprost wyprintowac trzeba by było iterowac przez wszystkie elementy, fetch_all zwraca to jako lista
czyli przykładem użycia tej funkcji to:
cursor = db.find("users")
print(db.fetch_all(cursor))

2024-10-29 11:04 UTC, julkry commented on controller/src/endpoints/user.py
> +        return users, 200
sprawdzac i robic konwersje jesli nie jest?

2024-10-29 14:46 UTC, Mazart23 commented on controller/src/endpoints/user.py
> +            api.abort(404, "User not found.")
Tak, chodzi o to że jeżeli nie ma url to jest wtedy Not found a jak nie ma usera to User  not found i wtedy na podstawie komunikatu stwierdzac co poszło nie tak. Po prostu trzeba sprawdzić w swaggerze czy jest ten komunikat User not found i czy front będzie w stanie wyciągnąć ten komunikat i zrobić walidacje na jego podstawie

2024-10-29 14:54 UTC, Mazart23 commented on controller/src/database/__init__.py
> +    def fetch_all(self, cursor):
Chyba że właśnie są jakieś inne metody które będziemy mogli wywoływać na cursorze to wtedy może zostać jak jest

2024-10-29 17:37 UTC, Mazart23 approved these changes

2024-10-29 17:40 UTC, Mazart23 commented on controller/src/endpoints/user.py
> +        return users, 200
Z tego co sprawdziłem teraz to find zawsze zwraca dict wiec nie trzeba

2024-10-31 07:23 UTC, Mazart23 approved these changes

2024-10-31 21:26 UTC, merged